#pragma once

#define PRECHARGE_CHECK_RISING_VOLTAGE 2
#define PRECHARGE_CHECK_AFTER_TIMEOUT 1
#define PRECHARGE_CHECK_NO_CHECK 0

#define PRECHARGE_CHECK PRECHARGE_CHECK_NO_CHECK

#define ACTIVE_DISCHARGE_CHECK 0

#define USING_CONTACTOR_LOW 0