#pragma once

#define ENABLE_PRECHARGE_CHECKS 0
#define SUPERCAPS_DISCHARGE_IS_NORMALLY_OPEN 1
#define USING_CONTACTOR_LOW_SIDE 0
#define USING_CONTACTOR_SUPERCAPS_CHARGE 0
#define USING_CONTACTOR_INVERSOR_DISCHARGE 0