name: C/C++ CI

on:
  push:
    branches: [ "main" ,"test_automated_build"]
  pull_request:
    branches: [ "main" ]

jobs:
  build_st_lib:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3 
       with:
          repository: HyperloopUPV-H8/ST-LIB 
          ref: 9a5647c0018067351c4c6cfc52dfdc500e56d347
     - run: |
        ls .
     - uses: HyperloopUPV-H8/ST-LIB/.github/workflows/c-cpp.yml@9a5647c0018067351c4c6cfc52dfdc500e56d347
  build:
    runs-on: ubuntu-latest
    needs: build_st_lib
    steps:
    - uses: actions/checkout@v3
    - name: check STLIB
      run: | 
        ls /opt/STLIB
    - name: Build project
      run: python3 tools/build.py -eth ON -t NUCLEO -bb Debug
