name: C/C++ CI

on:
  push:
    branches: [ "main" ,"test_automated_build"]
  pull_request:
    branches: [ "main" ]

jobs:
  build_st_lib:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3 
       with:
          repository: HyperloopUPV-H8/ST-LIB 
          ref: 9a5647c0018067351c4c6cfc52dfdc500e56d347
     - uses: carlosperate/arm-none-eabi-gcc-action@v1
     - run: arm-none-eabi-gcc --version
     - name: Install dependencies
       run: pip install GitPython colorama
     - name: Set up ST-LIB
       run: ls && cp -r ../* /opt/
     
     - run: echo pwd
     - name: Display ST-LIB
       working-directory: /opt/ST-LIB/
       run: ls 
     - name: Invoking python
       working-directory: /opt/ST-LIB/tools
       run: python3 build.py -eth ON -t NUCLEO -bb ${{matrix.build_type}}
     - name: Upload build artifact
       uses: actions/upload-artifact@v3
       with:
          name: library
          path: /opt/ST-LIB/build/${{matrix.build_type}}/lib/libst-lib.a
  build:
    runs-on: ubuntu-latest
    needs: build_st_lib
    steps:
    - uses: actions/checkout@v3
    - name: check STLIB
      run: | 
        ls /opt/STLIB
    - name: Build project
      run: python3 tools/build.py -eth ON -t NUCLEO -bb Debug
