name: C/C++ CI

on:
  push:
    branches: [ "main" ,"test_automated_build"]
  pull_request:
    branches: [ "main" ]

jobs:
  build_st_lib:
    uses: HyperloopUPV-H8/ST-LIB/.github/workflows/c-cpp.yml@d5361b8a7ed88a0f360a3c319f934e89f5b687b4
    with:
      repository: HyperloopUPV-H8/ST-LIB
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check STLIB
      run: | 
        ls /opt/STLIB
