name: C/C++ CI

on:
  push:
    branches: [ "main" ,"test_automated_build"]
  pull_request:
    branches: [ "main" ]

jobs:
  uses: HyperloopUPV-H8/ST-LIB/.github/workflows/c-cpp.yml@d5361b8a7ed88a0f360a3c319f934e89f5b687b4
  build:
    strategy:
      matrix: 
        build_type: [Debug, Release]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build STLIB
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
